### PR TITLE
Remove owner links

### LINKED ISSUE #47: Remove owner links
Owner pages are not supported by charmhub.io so they should be de-linked.

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Remove the owner link from the cards as they are no longer supported by charmhub.io

## QA
- Pull this branch
- Run `npm install`
- Run `npm run build`
- Open build/index.html

Fixes https://github.com/canonical-web-and-design/juju-cards/issues/47

### CODE REVIEW

**Review by jkfran — APPROVED** [review]
Code looks good to me but I am getting an error with npm

**Comment by jkfran** [comment]
Ok, I could do it with `yarn`.

The deploy buttons are also broken, the URL seems to have a difficult pattern to fix it with a redirect rule. It will be nice to point to charmhub, is it possible?

**Comment by anthonydillon** [comment]
Yeah, good catch

**Comment by anthonydillon** [comment]
@jkfran I have switched to using jaas.ai as charmhub doesn't have many of the charms and bundles used. I have removed the deploy button too.

**Review by jkfran — DISMISSED** [review]

**Review by jkfran — APPROVED** [review]
:+1:

**Pull request merged**
